name: Development.litleSpiderBot

on:
  push:
    branches:
      - dev
jobs:
    build:
      runs-on: ubuntu-latest, windows-latest
      strategy:
        fail-fast: false
        matrix:
          java: [11,17]
      steps:
        - uses: actions/checkout@v2
        - name: Set up JDK ${{ matrix.java }}
          uses: actions/setup-java@v2
          with:
            java-version: ${{ matrix.java }}
            distribution: 'adopt'
        - name: Build with Maven
          run: mvn -B package --file pom.xml
        - name: Run tests
          run: mvn -B test --file pom.xml
